require("lodash");
require("angular");
require("angular-simple-logger");
require("angular-animate");
require("angular-messages");
require("angular-route");
require("angular-ui-bootstrap");
// require("angular-google-maps");
require("leaflet");
require("angular-leaflet-directive");
